version: '3.8'
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,sqs,cognito
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4572:4572" # s3
      - "4576:4576" # sqs
volumes:
  db:
    driver: local