version: '3.8'

services:
  # MySQL
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"  # Expose a porta do MySQL


  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8079:8080"  # Expor a porta do Keycloak
    command: start-dev

  # Aplicativo Quarkus com integração Keycloak via OIDC
#  quarkus-app:
#    image: your-quarkus-app-image:latest  # Substitua pelo nome da imagem do seu aplicativo
#    container_name: quarkus-app
#    ports:
#      - "8081:8081"  # Expor a porta do seu aplicativo Quarkus
#    environment:
#      QUARKUS_OIDC_AUTH-server-url: ${QUARKUS_OIDC_AUTH-server-url}
#      QUARKUS_OIDC_AUTH-client-id: ${QUARKUS_OIDC_AUTH-client-id}
#      QUARKUS_OIDC_AUTH-client-secret: ${QUARKUS_OIDC_AUTH-client-secret}
#      QUARKUS_DATASOURCE_URL: ${QUARKUS_DATASOURCE_URL}
#      QUARKUS_DATASOURCE_DRIVER: ${QUARKUS_DATASOURCE_DRIVER}
#      QUARKUS_DATASOURCE_USERNAME: ${QUARKUS_DATASOURCE_USERNAME}
#      QUARKUS_DATASOURCE_PASSWORD: ${QUARKUS_DATASOURCE_PASSWORD}
#      QUARKUS_HTTP_PORT: ${QUARKUS_HTTP_PORT}
#    depends_on:
#      - keycloak  # Aguardar o Keycloak estar pronto antes de iniciar o aplicativo
