version: '3.8'

services:
  # MySQL
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"  # Expose a porta do MySQL
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  # Keycloak
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: ${KC_DB}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_PORT: ${KC_DB_URL_PORT}
      KC_DB_SCHEMA: ${KC_DB_SCHEMA}
    ports:
      - "8081:8081"  # Expor a porta do Keycloak
    depends_on:
      - mysql

  # Aplicativo Quarkus com integração Keycloak via OIDC
#  quarkus-app:
#    image: your-quarkus-app-image:latest  # Substitua pelo nome da imagem do seu aplicativo
#    container_name: quarkus-app
#    ports:
#      - "8081:8081"  # Expor a porta do seu aplicativo Quarkus
#    environment:
#      QUARKUS_OIDC_AUTH-server-url: ${QUARKUS_OIDC_AUTH-server-url}
#      QUARKUS_OIDC_AUTH-client-id: ${QUARKUS_OIDC_AUTH-client-id}
#      QUARKUS_OIDC_AUTH-client-secret: ${QUARKUS_OIDC_AUTH-client-secret}
#      QUARKUS_DATASOURCE_URL: ${QUARKUS_DATASOURCE_URL}
#      QUARKUS_DATASOURCE_DRIVER: ${QUARKUS_DATASOURCE_DRIVER}
#      QUARKUS_DATASOURCE_USERNAME: ${QUARKUS_DATASOURCE_USERNAME}
#      QUARKUS_DATASOURCE_PASSWORD: ${QUARKUS_DATASOURCE_PASSWORD}
#      QUARKUS_HTTP_PORT: ${QUARKUS_HTTP_PORT}
#    depends_on:
#      - keycloak  # Aguardar o Keycloak estar pronto antes de iniciar o aplicativo
